# sara attia abdel hamid

In [2]:
import tensorflow as tf
print(tf.__version__)
const_a = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32) # Create a 2x2 matrix with values 1, 2, 3, and 4.
const_a

2.1.0


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [3]:
# View common attributes.
print("value of const_a: ", const_a.numpy())
print("data type of const_a: ", const_a.dtype)
print("shape of const_a: ", const_a.shape)
print("device that const_a will be generated: ", const_a.device)

value of const_a:  [[1. 2.]
 [3. 4.]]
data type of const_a:  <dtype: 'float32'>
shape of const_a:  (2, 2)
device that const_a will be generated:  /job:localhost/replica:0/task:0/device:CPU:0


In [ ]:
#tf.zeros(), tf.zeros_like(), tf.ones(),tf.ones_like()

In [4]:
zeros_like_c = tf.zeros_like(const_a)
# View generated data.
zeros_like_c.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [5]:
#Create a tensor and fill it with a specific value.

In [6]:
fill_d = tf.fill([3,3], 8) # 3x3 matrix with all element values being 8
# View data.
fill_d.numpy()

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [7]:
# tf.random

In [8]:
random_e = tf.random.normal([5,5],mean=0,stddev=1.0, seed = 1)
# View the created data.
random_e.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

In [9]:
#Create a list object by using NumPy and then convert it into a tensor by using tf.convert_to_tensor...

In [10]:
# Create a list.
list_f = [1,2,3,4,5,6]
# View the data type.
type(list_f)

list

In [11]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [12]:
#Creating a Variable Tensor

In [13]:
var_1 = tf.Variable(tf.ones([2,3]))
var_1


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
# Read the variable value.
print("value of var_1: ",var_1.read_value())
# Assign a new value to the variable.
var_value_1=[[1,2,3],[4,5,6]] 
var_1.assign(var_value_1)
print("new value for var_1: ",var_1.read_value())

value of var_1:  tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]], shape=(2, 3), dtype=float32)
new value for var_1:  tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [15]:
# Add a value to this variable.
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [17]:
# Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.
tensor_h = tf.random.normal([4,100,100,3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-2.62390554e-01,  5.46806574e-01,  1.36366796e+00],
         [-1.21591938e+00,  6.83269441e-01, -1.35471082e+00],
         [-1.10969269e+00,  1.79963768e+00,  1.01061434e-01],
         ...,
         [ 4.60591853e-01,  1.61999059e+00, -1.94418237e-01],
         [-1.54489243e+00,  1.18613458e+00, -1.42518473e+00],
         [ 5.02152026e-01, -1.24685431e+00,  5.20179011e-02]],

        [[-3.78811330e-01,  4.24483744e-03, -8.79134595e-01],
         [ 1.22390234e+00, -1.01057911e+00,  6.50720537e-01],
         [ 9.06138003e-01,  9.09525692e-01, -3.24829847e-01],
         ...,
         [ 4.80694413e-01,  4.35404956e-01, -5.71509719e-01],
         [ 2.68860489e-01, -1.52718842e-01,  6.38414994e-02],
         [-2.62142920e+00, -3.36945832e-01,  2.29582056e-01]],

        [[-2.33346462e-01, -7.52712846e-01,  1.18434453e+00],
         [ 2.20879960e+00, -5.59145927e-01,  9.74691689e-01],
         [ 1.70472473e-01,  1.15510905e+00

In [18]:
# Extract the first image.
tensor_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-0.26239055,  0.5468066 ,  1.363668  ],
        [-1.2159194 ,  0.68326944, -1.3547108 ],
        [-1.1096927 ,  1.7996377 ,  0.10106143],
        ...,
        [ 0.46059185,  1.6199906 , -0.19441824],
        [-1.5448924 ,  1.1861346 , -1.4251847 ],
        [ 0.502152  , -1.2468543 ,  0.0520179 ]],

       [[-0.37881133,  0.00424484, -0.8791346 ],
        [ 1.2239023 , -1.0105791 ,  0.65072054],
        [ 0.906138  ,  0.9095257 , -0.32482985],
        ...,
        [ 0.4806944 ,  0.43540496, -0.5715097 ],
        [ 0.2688605 , -0.15271884,  0.0638415 ],
        [-2.6214292 , -0.33694583,  0.22958206]],

       [[-0.23334646, -0.75271285,  1.1843445 ],
        [ 2.2087996 , -0.5591459 ,  0.9746917 ],
        [ 0.17047247,  1.155109  , -0.16819187],
        ...,
        [ 0.73121303, -1.9723366 , -1.3172088 ],
        [-0.18951547,  0.95257866,  1.2118515 ],
        [-1.6024392 , -1.1387293 , -1.6905768 ]],

       ...,

     

In [19]:
# Extract one slice every two images.
tensor_h[::2,...]


<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.26239055,  0.5468066 ,  1.363668  ],
         [-1.2159194 ,  0.68326944, -1.3547108 ],
         [-1.1096927 ,  1.7996377 ,  0.10106143],
         ...,
         [ 0.46059185,  1.6199906 , -0.19441824],
         [-1.5448924 ,  1.1861346 , -1.4251847 ],
         [ 0.502152  , -1.2468543 ,  0.0520179 ]],

        [[-0.37881133,  0.00424484, -0.8791346 ],
         [ 1.2239023 , -1.0105791 ,  0.65072054],
         [ 0.906138  ,  0.9095257 , -0.32482985],
         ...,
         [ 0.4806944 ,  0.43540496, -0.5715097 ],
         [ 0.2688605 , -0.15271884,  0.0638415 ],
         [-2.6214292 , -0.33694583,  0.22958206]],

        [[-0.23334646, -0.75271285,  1.1843445 ],
         [ 2.2087996 , -0.5591459 ,  0.9746917 ],
         [ 0.17047247,  1.155109  , -0.16819187],
         ...,
         [ 0.73121303, -1.9723366 , -1.3172088 ],
         [-0.18951547,  0.95257866,  1.2118515 ],
         [-1.6024392 , -1.1387293 , -1.6905768

In [20]:
# Slice data from the last element.
tensor_h[::-1]


<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.30436838e-01,  5.28945208e-01, -1.72601998e-01],
         [-1.70503807e+00, -3.08392286e-01,  1.48279622e-01],
         [ 1.03464174e+00, -2.67863870e-01,  2.05137038e+00],
         ...,
         [ 1.79180540e-02, -7.27092087e-01,  1.17629528e+00],
         [-3.13840300e-01,  1.30668497e+00, -3.88866246e-01],
         [-1.25780189e+00, -1.58691719e-01,  1.30143189e+00]],

        [[-6.71276927e-01, -3.88955116e+00, -3.60441715e-01],
         [ 9.63085532e-01, -1.04946637e+00, -7.18491256e-01],
         [-6.32096946e-01, -4.83431488e-01,  1.13979876e+00],
         ...,
         [ 1.44856977e+00,  3.36182356e-01,  1.64431465e+00],
         [-8.26878250e-01,  1.75918663e+00, -4.96632576e-01],
         [ 2.65656918e-01, -9.47974384e-01, -1.21705544e+00]],

        [[ 2.30841112e+00, -1.39468700e-01, -8.88733506e-01],
         [ 7.53376722e-01,  3.54945481e-01,  7.40946889e-01],
         [ 2.44849539e+00, -1.45202741e-01

In [21]:
#indexing

In [22]:
# Obtain the pixel in the [20,40] position in the second channel of the first image.
tensor_h[0][19][39][1]


<tf.Tensor: shape=(), dtype=float32, numpy=-0.733667>

In [24]:
# Extract the first, second, and fourth images from tensor_h ([4,100,100,3]).
indices = [0,1,3]
tf.gather(tensor_h,axis=0,indices=indices)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[-2.62390554e-01,  5.46806574e-01,  1.36366796e+00],
         [-1.21591938e+00,  6.83269441e-01, -1.35471082e+00],
         [-1.10969269e+00,  1.79963768e+00,  1.01061434e-01],
         ...,
         [ 4.60591853e-01,  1.61999059e+00, -1.94418237e-01],
         [-1.54489243e+00,  1.18613458e+00, -1.42518473e+00],
         [ 5.02152026e-01, -1.24685431e+00,  5.20179011e-02]],

        [[-3.78811330e-01,  4.24483744e-03, -8.79134595e-01],
         [ 1.22390234e+00, -1.01057911e+00,  6.50720537e-01],
         [ 9.06138003e-01,  9.09525692e-01, -3.24829847e-01],
         ...,
         [ 4.80694413e-01,  4.35404956e-01, -5.71509719e-01],
         [ 2.68860489e-01, -1.52718842e-01,  6.38414994e-02],
         [-2.62142920e+00, -3.36945832e-01,  2.29582056e-01]],

        [[-2.33346462e-01, -7.52712846e-01,  1.18434453e+00],
         [ 2.20879960e+00, -5.59145927e-01,  9.74691689e-01],
         [ 1.70472473e-01,  1.15510905e+00

In [27]:
# Extract the pixel in [1,1] in the first dimension of the first image and pixel in [2,2] in the first dimension of the second image in tensot_h ([4,100,100,3])
indices = [[0,1,1,0],[1,2,2,0]]
tf.gather_nd(tensor_h,indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2239023, 0.0269038], dtype=float32)>

In [28]:
#Tensor Dimension Modification

In [29]:
const_d_1 = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32)
# Three common methods for displaying a dimension:
print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1))
# The output is a tensor. The value of the tensor indicates the size of the tensor dimension to be displayed

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [30]:
#Dimension Reshaping


In [32]:
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)
tf.reshape(reshape_1, (3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [37]:
# Dimension Expansion
# Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("original data size: ",expand_sample_1.shape)
print("add a dimension (axis=0) before the first dimension: ",tf.expand_dims(expand_sample_1, axis=0).shape)
print("add a dimension (axis=1) before the second dimension: ",tf.expand_dims(expand_sample_1, axis=1).shape)
print("add a dimension (axis=-1) after the last dimension: ",tf.expand_dims(expand_sample_1, axis=-1).shape)


original data size:  (100, 100, 3)
add a dimension (axis=0) before the first dimension:  (1, 100, 100, 3)
add a dimension (axis=1) before the second dimension:  (100, 1, 100, 3)
add a dimension (axis=-1) after the last dimension:  (100, 100, 3, 1)


In [35]:
# Generate a 100 x 100 x 3 tensor.
orig_sample_1 = tf.random.normal([1,100,100,3])
print("original data size: ",orig_sample_1.shape)
squeezed_sample_1 = tf.squeeze(orig_sample_1)
print("squeezed data size: ",squeezed_sample_1.shape)
# The dimension of 'squeeze_sample_2' is [1, 2, 1, 3, 1, 1].
squeeze_sample_2 = tf.random.normal([1, 2, 1, 3, 1, 1])
t_1 = tf.squeeze(squeeze_sample_2) # Dimensions of size 1 are removed.
print('t_1.shape:', t_1.shape)
# Remove a specific dimension:
# 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
t_1_new = tf.squeeze(squeeze_sample_2, [2, 4])
print('t_1_new.shape:', t_1_new.shape)

original data size:  (1, 100, 100, 3)
squeezed data size:  (100, 100, 3)
t_1.shape: (2, 3)
t_1_new.shape: (1, 2, 3, 1)


In [38]:
# Generate a 100 x 100 x 3 tensor.
orig_sample_1 = tf.random.normal([1,100,100,3])
print("original data size: ",orig_sample_1.shape)
squeezed_sample_1 = tf.squeeze(orig_sample_1)
print("squeezed data size: ",squeezed_sample_1.shape)
# The dimension of 'squeeze_sample_2' is [1, 2, 1, 3, 1, 1].
squeeze_sample_2 = tf.random.normal([1, 2, 1, 3, 1, 1])
t_1 = tf.squeeze(squeeze_sample_2) # Dimensions of size 1 are removed.
print('t_1.shape:', t_1.shape)
# Remove a specific dimension:
# 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
t_1_new = tf.squeeze(squeeze_sample_2, [2, 4]) 
print('t_1_new.shape:', t_1_new.shape)

original data size:  (1, 100, 100, 3)
squeezed data size:  (100, 100, 3)
t_1.shape: (2, 3)
t_1_new.shape: (1, 2, 3, 1)


In [39]:
# Low-dimensional transposition is simple. Input the tensor to be transposed by calling tf.transpose.
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data size: ",trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("transposed data size: ",transposed_sample_1.shape)

original data size:  (2, 3)
transposed data size:  (3, 2)


In [40]:
#The perm parameter is required for transposing high-dimensional data. perm indicates the permutation of the
#dimensions of the input tensor.
#For a three-dimensional tensor, its original dimension permutation is [0, 1, 2] (perm), indicating the length, width,
#and height of the high-dimensional data, respectively.
#By changing the value sequence in perm, you can transpose the corresponding dimension of the data.
# Generate a 4 x 100 x 200 x 3 tensor to represent four 100 x 200 three-channel color images.
trans_sample_2 = tf.random.normal([4,100,200,3])
print("original data size: ",trans_sample_2.shape)
# Exchange the length and width of the four images. The value range of perm is changed from [0,1,2,3] to[0,2,1,3].
transposed_sample_2 = tf.transpose(trans_sample_2,[0,2,1,3])
print("transposed data size: ",transposed_sample_2.shape)

original data size:  (4, 100, 200, 3)
transposed data size:  (4, 200, 100, 3)


In [41]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data: ",broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
print("broadcast data: ",broadcasted_sample_1.numpy())

original data:  [1 2 3 4 5 6]
broadcast data:  [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [42]:
# During the operation, if two arrays have different shapes, TensorFlow automatically triggers the broadcast mechanism as NumPy does.
a = tf.constant([[ 0, 0, 0],[10,10,10],[20,20,20],[30,30,30]])
b = tf.constant([1,2,3])
print(a + b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [43]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))


tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [44]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]])>

In [45]:
argmax_sample_1 = tf.constant([[1,3,2],[2,5,8],[7,5,9]])
print("input tensor: ",argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by column: ",max_sample_1.numpy())
print("locate the maximum value by row: ",max_sample_2.numpy())

input tensor:  [[1 3 2]
 [2 5 8]
 [7 5 9]]
locate the maximum value by column:  [2 1 2]
locate the maximum value by row:  [1 2 2]


In [47]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("original data size: ",concat_sample_1.shape,concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("concatenated data size: ",concated_sample_1.shape)

original data size:  (4, 100, 100, 3) (40, 100, 100, 3)
concatenated data size:  (44, 100, 100, 3)


In [49]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("original data size: ",concat_sample_1.shape,concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("concatenated data size: ",concated_sample_1.shape)

original data size:  (4, 100, 100, 3) (40, 100, 100, 3)
concatenated data size:  (44, 100, 100, 3)


In [51]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("original data size: ",stack_sample_1.shape, stack_sample_2.shape)
# Dimension addition after concatenating. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("concatenated data size: ",stacked_sample_1.shape)

original data size:  (100, 100, 3) (100, 100, 3)
concatenated data size:  (2, 100, 100, 3)


In [52]:
# Unpack data along the first dimension and output the unpacked data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-1.29773986e+00, -1.16767240e+00, -6.98564529e-01],
         [-2.93079376e+00,  4.92328793e-01, -6.16120160e-01],
         [-6.67155564e-01, -4.07252103e-01,  3.63552779e-01],
         ...,
         [ 8.02967101e-02,  1.47458434e+00, -7.97317624e-01],
         [-5.84796250e-01, -8.26226771e-02, -3.19255322e-01],
         [-6.93012416e-01, -1.16392982e+00,  1.89343584e+00]],
 
        [[-3.03642333e-01, -4.79386032e-01, -1.69732943e-02],
         [ 2.65886575e-01,  2.74941772e-01, -5.37411273e-01],
         [ 6.45253599e-01,  7.55726825e-03, -3.87790114e-01],
         ...,
         [ 1.14624429e+00,  2.25185350e-01,  1.12820959e+00],
         [-2.44741723e-01,  8.77404273e-01, -5.75264633e-01],
         [ 1.64698660e+00, -4.58449066e-01, -5.39609611e-01]],
 
        [[ 5.11499643e-01,  2.49364123e-01, -4.39564772e-02],
         [ 1.00114775e+00, -2.00522039e-03, -1.62259388e+00],
         [-8.56646240e-01, -2.35540912e-01

In [53]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print("original data size: ",split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("If m_or_size_splits is 5, the size of the split data is: ",np.shape(splited_sample_1))
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("If num_or_size_splits is [3,5,2], the sizes of the split data are:",
np.shape(splited_sample_2[0]),
np.shape(splited_sample_2[1]),
np.shape(splited_sample_2[2]))

original data size:  (10, 100, 100, 3)
If m_or_size_splits is 5, the size of the split data is:  (5, 2, 100, 100, 3)
If num_or_size_splits is [3,5,2], the sizes of the split data are: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [54]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor: ",sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order: ",sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("index of elements in ascending order: ",sorted_sample_2.numpy())

input tensor:  [8 1 0 7 5 4 3 9 2 6]
tensor sorted in ascending order:  [0 1 2 3 4 5 6 7 8 9]
index of elements in ascending order:  [2 1 8 6 5 4 9 3 0 7]


In [55]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor: ",sort_sample_1.numpy())
print("k largest values in ascending order: ", values.numpy())
print("indices of the k largest values in ascending order: ", index.numpy())

input tensor:  [8 1 0 7 5 4 3 9 2 6]
k largest values in ascending order:  [9 8 7 6 5]
indices of the k largest values in ascending order:  [7 0 3 9 4]


In [56]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2],
[3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [57]:
import tensorflow as tf
thre_1 = tf.random.uniform([], 0, 1)
x = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)
if thre_1.numpy() > 0.5:
    y = tf.matmul(x, x)
else:
    y = tf.add(x, x)

tf.Tensor(0.2210052, shape=(), dtype=float32)


In [58]:
@tf.function
def simple_nn_layer(w,x,b):
    print(b)
    return tf.nn.relu(tf.matmul(w, x)+b)

w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')
simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.4706595, 1.0209495, 0.9760246],
       [1.7954406, 1.209602 , 1.2038367],
       [1.8980311, 1.2382371, 1.1822026]], dtype=float32)>